GET http://localhost:3000/api/contacts

###
GET http://localhost:3000/api/contacts/5d42b22b59a818142ae0e6d6
Content-Type: application/json

###
PATCH  http://localhost:3000/api/contacts/5d42b22b59a818142ae0e6d6
Content-Type: application/json

{
    "name": "Ken Jannsen",
    "email": "kenjan@gmail.com"
}